# Generated by Django 4.1.1 on 2022-09-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-date_uploaded']},
        ),
    ]
